'use strict';
const assert=require('node:assert/strict');
const {evaluate,buildSocPlan}=require('../lib/ems-engine');
const now=new Date('2026-09-25T01:00:00Z');
const settings={timezone:'UTC',batteryCount:1,totalCapacityKwh:20,minSoc:10,maxSoc:100,maxTotalChargeW:4000,maxChargePerBatteryW:4000,forcedMode:'auto',contractType:'dynamic_hour',dynamicPriceDataReady:true,forecastDataReady:true,forecastDailyDataReady:true,expectedEnergyNeedKwh:20,cheapHours:1,expensiveHours:1,nightTargetTime:'07:00',dynamicNormalChargeEnabled:true,dynamicNormalChargeMaxSoc:40,dynamicSlots:Array.from({length:24},(_,h)=>({time:`${String(h).padStart(2,'0')}:00`,price:h===13?.05:h===18?.50:.20+h*.001}))};
const state={gridPowerW:0,pvPowerW:0,forecastRemainingKwh:0,forecastDailyMaxKwh:0,batterySoc:[20],lastTotalCommandW:0,nightPlanningActive:true,planningForecastDay:'today'};
let result=evaluate(state,settings,now);console.log('live',result.baseMode,result.mode,result.totalCommandW,result.plannedChargeW);
assert(result.plannedChargeW>0);
for(const soc of [40,50])assert.equal(evaluate({...state,batterySoc:[soc]},settings,now).plannedChargeW,0);
assert.equal(evaluate(state,{...settings,dynamicNormalChargeEnabled:false},now).plannedChargeW,0);
assert.equal(evaluate(state,{...settings,dynamicPriceDataReady:false},now).plannedChargeW,0);
let plan=buildSocPlan(state,settings,now);
assert(plan.rows.length>0);assert(plan.rows.every(r=>r.endAt<=Date.parse('2026-09-25T07:00:00Z')));
assert(plan.rows.some(r=>r.tariffLabel==='Normaal'&&r.plannedNetCharge));
assert(plan.rows.every(r=>r.socTarget<=40));
assert(plan.rows.reduce((n,r)=>n+r.plannedEnergyKwh,0)<=4.01);
assert.equal(buildSocPlan(state,{...settings,dynamicNormalChargeEnabled:false},now).nextNetChargeAt,null);
const cheap=evaluate({...state,batterySoc:[50],nightPlanningActive:false},settings,new Date('2026-09-25T13:00:00Z'));assert(cheap.plannedChargeW>0);
const noNeed=evaluate({...state,targetSocOverride:15},settings,now);assert.equal(noNeed.plannedChargeW,0);
console.log('0.8.7: normal charging opt-in, SoC ceiling, deadline, cheap charging and missing prices passed');
const pv=evaluate({...state,batterySoc:[50],gridPowerW:-1500,pvPowerW:1500},settings,now);assert(pv.totalCommandW<0,'PV capture remains possible above normal grid-charge ceiling');
const peak=evaluate({...state,gridPowerW:2400},{...settings,peakShaveEnabled:true,peakLimitW:2500,peakSoftMarginW:100},now);assert(peak.totalCommandW>=-1,'Peak Guard must prevent additional grid charging at its margin');
(async()=>{
 const {boot}=require('./startup-harness');
 let b=await boot();assert.equal(b.store.get('dynamicNormalChargeEnabled'),false);assert.equal(b.store.get('dynamicNormalChargeMaxSoc'),50);
 const saved=new Map([['dynamicNormalChargeEnabled',true],['dynamicNormalChargeMaxSoc',37],['peakLimitW',2700]]);
 b=await boot(saved);assert.equal(b.store.get('dynamicNormalChargeEnabled'),true);assert.equal(b.store.get('dynamicNormalChargeMaxSoc'),37);assert.equal(b.store.get('peakLimitW'),2700);
 console.log('0.8.7: PV capture, Peak Guard and settings persistence passed');
})().catch(e=>{console.error(e);process.exitCode=1});
