'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const settingsHtml = fs.readFileSync(path.join(root, 'settings', 'index.html'), 'utf8');
const runtimeFiles = [
  'app.js',
  'api.js',
  'lib/ems-engine.js',
  'lib/flexible-loads.js',
  'lib/homey-energy.js',
  'lib/savings.js',
  'widgets/savings/api.js',
];
const runtimeText = runtimeFiles
  .map(file => fs.readFileSync(path.join(root, file), 'utf8'))
  .join('\n');

function literalArray(name) {
  const pattern = new RegExp(`const ${name} = \\[([\\s\\S]*?)\\];`);
  const match = settingsHtml.match(pattern);
  assert.ok(match, `settings array ${name} must exist`);
  return [...match[1].matchAll(/'([^']+)'/g)].map(item => item[1]);
}

const persisted = new Set(literalArray('ids'));
const evSuffixes = literalArray('evSuffixes');
const hvacSuffixes = literalArray('hvacSuffixes');

for (let instance = 1; instance <= 4; instance += 1) {
  const evStem = instance === 1 ? 'ev' : `ev${instance}`;
  for (const suffix of evSuffixes) persisted.add(`${evStem}${suffix}`);
  const hvacStem = instance === 1 ? 'hvac' : `hvac${instance}`;
  for (const suffix of hvacSuffixes) persisted.add(`${hvacStem}${suffix}`);
}

const splitSuffixes = [
  'Enabled', 'ChargePowerPositive', 'KeepMinimumPower', 'MinimumPowerW', 'ZeroMode',
  'ChargeMinSwitchSeconds', 'DischargeMinSwitchSeconds', 'MinBetweenSwitchSeconds',
  'DirectionConfirmSeconds', 'SafetyModeResendEnabled', 'SafetyModeResendMinutes',
];
for (let battery = 1; battery <= 8; battery += 1) {
  persisted.add(`battery${battery}MaxChargeW`);
  persisted.add(`battery${battery}MaxDischargeW`);
  for (const suffix of splitSuffixes) persisted.add(`splitCommandBattery${battery}${suffix}`);
}

// Every real settings field marked in the UI must be part of the persisted set.
const formIds = new Set(
  [...settingsHtml.matchAll(/<(?:input|select|textarea)\b[^>]*\bid="([^"]+)"[^>]*>/g)]
    .map(match => match[1]),
);
const settingMarkers = [...settingsHtml.matchAll(/data-setting-id="([^"]+)"/g)].map(match => match[1]);
for (const id of settingMarkers) {
  if (!formIds.has(id)) continue; // group/container marker, not a value itself
  assert.ok(persisted.has(id), `UI setting ${id} must be persisted`);
}

// Conversely, every persisted setting generated by the page must still have a form field.
for (const id of persisted) assert.ok(formIds.has(id), `persisted setting ${id} must have a UI field`);

// Top-level settings must have a runtime consumer outside the settings page.
for (const key of literalArray('ids')) {
  assert.ok(runtimeText.includes(key), `setting ${key} has no runtime consumer`);
}

// Multi-instance settings are normalised to evX/hvacX names by the app. Verify
// that each exposed suffix maps to a generic runtime field that is actually used.
for (const suffix of evSuffixes) {
  assert.ok(runtimeText.includes(`ev${suffix}`), `EV setting suffix ${suffix} has no runtime consumer`);
}
for (const suffix of hvacSuffixes) {
  assert.ok(runtimeText.includes(`hvac${suffix}`), `HVAC setting suffix ${suffix} has no runtime consumer`);
}

// Split-command settings use template keys, so verify the dynamic runtime path.
for (const suffix of splitSuffixes) {
  assert.ok(
    runtimeText.includes(`splitCommandBattery\${battery}${suffix}`),
    `split-command setting suffix ${suffix} has no runtime consumer`,
  );
}

console.log(`settings runtime audit passed (${persisted.size} persisted UI settings)`);
